version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    ports:
      - "6379:6379"

  mysql:
    restart: always
    image: mysql:8
    container_name: exchange-bank
    hostname: exchange-bank
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=dubai_exchange
    ports:
      - "3306:3306"