spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://db-mysql-fra1-46801-do-user-13021607-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED
    username: doadmin
    password: AVNS_KSwiCuPa41g7vZ-tf0K
    driverClassName: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
api:
  telegram:
    bot-token: 5915751985:AAFnc8bT4_iYVI4ILXnJRRqeegCH3vkfgeM
springfox:
  documentation:
    swagger-ui:
      enabled: true
