spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/lead-booster
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
api:
  telegram:
    enabled: false
    bot-token: 5915751985:AAFnc8bT4_iYVI4ILXnJRRqeegCH3vkfgeM