server:
  port: 9090

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    url: ${DB_URL}
    username: doadmin
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
api:
  telegram:
    enabled: true
    bot-token: ${BOT_TOKEN}
